# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='caterory',
            new_name='category',
        ),
    ]
